### ISSUE TITLE
Typo in Zamfara and Akwa Ibom Spelling, Also typo in Onuimo LGA of Imo State

### ISSUE THREAD

**Issue by prondubuisi** [CeoFred/dropdown_for_states_and_lga_in_nigeria#1]
https://en.wikipedia.org/wiki/Imo_State
https://en.wikipedia.org/wiki/States_of_Nigeria

**Comment by CeoFred** [comment]
Thank you for looking in between the lines,you must be from onuimo

**Comment by prondubuisi** [comment]
No. Am from Ideato
